name: Build and publish library

on:
  push:
    branches: ['main']
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[docs]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.8.1
      - run: bun install --frozen-lockfile
      - run: bun run tsc
      - run: bun run build-cli
      - run: cp tsm tsm-cli/bin/tsm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@navikt'
      - run: npm publish
        if: github.ref == 'refs/heads/main'
        working-directory: ./tsm-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  increment-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup github connection for auth
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: jq --arg version "1.0.$(date +%F-%H%M)" '.version = $version' package.json > updated.json && mv updated.json package.json
      - run: git add . && git commit -m "[skip ci] bump version to $(jq -r .version package.json)" && git push
